name: binance-client
channels:
  - conda-forge
  - defaults
  - districtdatalabs
dependencies:
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - scikit-learn
  - python-lsp-server
  - yellowbrick
  - matplotlib
  - statsmodels
